# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Abhirath Anand
email: theabhirathanand@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  CS Junior at BITS Pilani. Interested in machine learning and deep learning research.
twitter_username: theabhirath
github_username: theabhirath
search: true
repository: "theabhirath/theabhirath.github.io"
logo: "/assets/images/aesthetic.png"

minimal_mistakes_skin: "default"

# Build settings
markdown: kramdown
kramdown:
    syntax_highlighter_opts:
      disable: true
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
timezone: Asia/Kolkata

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Abhirath Anand"
  avatar : "/assets/images/bio-photo.png"
  bio    : "CS Junior at BITS Pilani. Interested in machine learning and deep learning research."
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/theabhirath"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/theabhirathanand/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter"
      url: "https://twitter.com/theabhirath"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/theabhirathanand/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter"
      url: "https://twitter.com/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      show_date: true
      author_profile: true
      read_time: true
      comments: true
      share: false
      classes: wide
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

comments:
  provider: "giscus"
  giscus:
    repo_id              : "R_kgDOHbjPIA" # Shown during giscus setup at https://giscus.app
    category_name        : "General" # Full text name of the category
    category_id          : "DIC_kwDOHbjPIM4CPaA5" # Shown during giscus setup at https://giscus.app
    discussion_term      : "title" # "pathname" (default), "url", "title", "og:title"
    reactions_enabled    : "1" # '1' for enabled (default), '0' for disabled
    theme                : "light" # "light" (default), "dark", "dark_dimmed", "transparent_dark", "preferred_color_scheme"

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
